DefaultContentLanguage = "fi"
baseurl = "/"
canonifyurls = true
languagecode = "fi"
paginate = 10
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "b2"
theme = "lumikello"
title = "Lumikello ry"
[languages.en]
contentDir = "content/en"
languagename = "English"
[[languages.en.menu.main]]
name = "About"
url = "/page/about/"
weight = 1
[[languages.en.menu.main]]
name = "Calendar"
url = "/page/calendar/"
weight = 2
[[languages.en.menu.main]]
name = "Statute"
url = "/page/statute/"
weight = 2
[[languages.en.menu.main]]
name = "Contacts"
url = "/page/contacts/"
weight = 3
[[languages.en.menu.main]]
name = "Partners"
url = "/page/partners/"
weight = 4
[languages.en.params]
address = "Kuopio, Finland"
author = "Lumikello ry"
dateformat = "January 2, 2006"
description = "non-profit charity organization Lumikello Ry"
info = ""
keywords = "non-profit,charity,Lumikello,Kuopio,Suomi"
menu = "menu"
[languages.fi]
contentDir = "content/fi"
languagename = "Suomi"
[[languages.fi.menu.main]]
name = "Me"
url = "/page/about/"
weight = 1
[[languages.fi.menu.main]]
name = "Kalenteri"
url = "/page/calendar/"
weight = 2
[[languages.fi.menu.main]]
name = "Perustamiskirja"
url = "/page/statute/"
weight = 2
[[languages.fi.menu.main]]
name = "Tietosuojaseloste"
url = "/page/dataprotection/"
weight = 2
[[languages.fi.menu.main]]
name = "Yhteistiedot"
url = "/page/contacts/"
weight = 3
[[languages.fi.menu.main]]
name = "Yhteistyökumppanit"
url = "/page/partners/"
weight = 4
[languages.fi.params]
address = "Kuopio, Suomi"
author = "Lumikello ry"
dateformat = "2 January 2006"
description = "yleishyödyllinen hyväntekeväisyyden liitto Lumikello Ry"
info = ""
keywords = "kansalaisjärjestö,yleishyödyllisyys,hyväntekeväisyys,Lumikello,Kuopio,Suomi"
menu = "valikko"
[languages.ru]
contentDir = "content/ru"
languagename = "Русский"
[[languages.ru.menu.main]]
name = "О нас"
url = "/page/about/"
weight = 1
[[languages.ru.menu.main]]
name = "Календарь"
url = "/page/calendar/"
weight = 2
[[languages.ru.menu.main]]
name = "Практика у нас"
url = "/page/practice/"
weight = 2
[[languages.ru.menu.main]]
name = "Устав"
url = "/page/statute/"
weight = 2
[[languages.ru.menu.main]]
name = "Контакты"
url = "/page/contacts/"
weight = 3
[[languages.ru.menu.main]]
name = "Партнёры"
url = "/page/partners/"
weight = 4
[languages.ru.params]
address = "Куопио, Финляндия"
author = "Lumikello ry"
dateformat = "2 January 2006"
description = "благотворительная организация Lumikello ry"
info = ""
keywords = "благотворительная организация,благотворительномть,Лумикелло,Lumikello,Куопио,Финляндия"
menu = "меню"
[params]
author = "Lumikello ry"
avatar = "images/logo.svg"
businessid = "Y-tunnus 2819071-5"
custom_css = []
hideCopyright = false
hideCredits = false
rtl = false
[[params.social]]
icon = ""
name = "ВКонтакте"
url = "https://vk.com/lumikellory"
weight = ""
[[params.social]]
icon = ""
name = "Facebook "
url = "https://www.facebook.com/lumikellory/?ref=bookmarks"
weight = ""
[[params.social]]
icon = "fab fa-github"
name = "Github"
url = "https://github.com/johndoe/"
weight = 1
[[params.social]]
icon = "fab fa-gitlab"
name = "Gitlab"
url = "https://gitlab.com/johndoe/"
weight = 2
[[params.social]]
icon = "fab fa-twitter"
name = "Twitter"
url = "https://twitter.com/johndoe/"
weight = 3
[[params.social]]
icon = "fab fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/johndoe/"
weight = 4
[[params.social]]
icon = "fab fa-medium"
name = "Medium"
url = "https://medium.com/@johndoe"
weight = 5
