baseurl = "/"
title = "Lumikello Ry"

theme = "lumikello"

languagecode = "fi"
DefaultContentLanguage = "fi"

paginate = 10
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Lumikello Ry"
    avatar = "images/logo.svg"

    businessid = "Y-tunnus 2819071-5"

    hideCredits = false
    hideCopyright = false

    rtl = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/johndoe/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/johndoe/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@johndoe"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        contentDir = "content/en"

        [languages.en.params]
            author = "Lumikello Ry"
            address = "Kuopio, Finland"
            description = "non-profit charity organization Lumikello Ry"
            keywords = "non-profit,charity,Lumikello,Kuopio,Suomi"
            info = ""
            menu = "menu"

        dateformat = "January 2, 2006"

        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "About"
                weight = 1.0
                url = "/page/about/"
            [[languages.en.menu.main]]
                name = "Calendar"
                weight = 2.0
                url = "/page/calendar/"
            [[languages.en.menu.main]]
                name = "Statute"
                weight = 2.0
                url = "/page/statute/"

    [languages.ru]
        languagename = "Русский"
        contentDir = "content/ru"

        [languages.ru.params]
            author = "Лумикелло Рю"
            address = "Куопио, Финляндия"
            description = "благотворительная организация Лумикелло Рю"
            keywords = "благотворительная организация,благотворительномть,Лумикелло,Lumikello,Куопио,Финляндия"
            info = ""
            menu = "меню"

        dateformat = "2 January 2006"

        [languages.ru.menu]

            [[languages.ru.menu.main]]
                name = "О нас"
                weight = 1.0
                url = "/page/about/"
            [[languages.ru.menu.main]]
                name = "Календарь"
                weight = 2.0
                url = "/page/calendar/"
            [[languages.ru.menu.main]]
                name = "Устав"
                weight = 2.0
                url = "/page/statute/"

    [languages.fi]
        languagename = "Suomi"
        contentDir = "content/fi"

        [languages.fi.params]
            author = "Lumikello Ry"
            address = "Kuopio, Suomi"
            description = "yleishyödyllinen hyväntekeväisyyden liitto Lumikello Ry"
            keywords = "kansalaisjärjestö,yleishyödyllisyys,hyväntekeväisyys,Lumikello,Kuopio,Suomi"
            info = ""
            menu = "valikko"

        dateformat = "2 January 2006"

        [languages.fi.menu]

            [[languages.fi.menu.main]]
                name = "Me"
                weight = 1.0
                url = "/page/about/"
            [[languages.fi.menu.main]]
                name = "Kalenteri"
                weight = 2.0
                url = "/page/calendar/"
            [[languages.fi.menu.main]]
                name = "Perustamiskirja"
                weight = 2.0
                url = "/page/statute/"
            [[languages.fi.menu.main]]
                name = "Tietosuojaseloste"
                weight = 2.0
                url = "/page/dataprotection/"
