---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: config.toml
  label: conf
- type: directory
  path: content/fi
  label: FI
  create: all
  match: "**/*"
- type: directory
  path: content/en
  label: EN
  create: all
  match: "**/*"
- type: directory
  path: content/ru
  label: RU
  create: documents
  match: "**/*"
- type: directory
  path: themes/lumikello/i18n
  label: i18n
  create: documents
  match: "**/*"
  new_doc_ext: yaml
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.52'
