---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/fi
  label: FI
  create: all
  match: "**/*"
- type: directory
  path: content/en
  label: EN
  create: all
  match: "**/*"
- type: directory
  path: content/ru
  label: RU
  create: documents
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.49'
