---
label: Project
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  hidden: false
  config:
    required: true
- type: number
  name: weight
  label: Order
  config:
    required: false
  default: '1'
- type: textarea
  label: Description
  name: description
  config:
    wysiwyg: true
    schema:
      format: markdown
- type: file
  label: Picture
  name: picture
pages:
- content/en/project/ru-culture-studio.md
- content/ru/project/porcelain-studio.md
- content/fi/project/porcelain-studio.md
- content/ru/project/direct-aid.md
- content/en/project/direct-aid.md
- content/en/project/finnish-advanced.md
- content/fi/project/finnish-advanced.md
- content/en/project/adaptation-camp.md
- content/fi/project/adaptation-camp.md
- content/en/project/theatre.md
- content/ru/project/dance-school.md
- content/en/project/dance-school.md
- content/fi/project/dance-school.md
- content/ru/project/art-studio.md
- content/en/project/art-studio.md
- content/en/project/somatics.md
- content/ru/project/somatics.md
- content/en/project/porcelain-studio.md
- content/fi/project/art-studio.md
- content/fi/project/ru-culture-studio.md
- content/ru/project/finnish-advanced.md
- content/fi/project/direct-aid.md
- content/ru/project/ru-culture-studio.md
- content/ru/project/theatre.md
- content/ru/project/adaptation-camp.md
- content/ru/project/эко-клуб-yellow-jackets.md
- content/fi/project/theatre.md
- content/fi/project/somatics.md
